name = "Darkdoc"
license = "MIT"
licenselink = "https://github.com/adejoux/hugo-darkdoc/blob/master/LICENSE.md"
description = "bootstrap theme for documentation"
homepage = "https://github.com/adejoux/hugo-darkdoc"
tags = ["bootstrap", "documentation", "responsive"]
features = ["", ""]
min_version = 0.14

[author]
  name = "Alain Dejoux"
  homepage = "http://djouxtech.net"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
